import { Pool } from 'pg';
import { PrismaPg } from '@prisma/adapter-pg';
import type { Prisma } from '@prisma/client';

// PrismaClient is generated by Prisma and available at runtime
const { PrismaClient } = require('@prisma/client') as {
  PrismaClient: new (args?: { adapter?: PrismaPg }) => Prisma.DefaultPrismaClient;
};

const connectionString = process.env.DATABASE_URL!;
if (!connectionString) {
  throw new Error('DATABASE_URL environment variable is not set');
}

const pool = new Pool({ connectionString });
const adapter = new PrismaPg(pool);

const prisma = new PrismaClient({ adapter });

export default prisma;

